#ifndef BLADE_ATA_MODE_A_CONFIG_H
#define BLADE_ATA_MODE_A_CONFIG_H

#define BLADE_ATA_MODE_A_CHANNELIZER_RATE 1 // [1, 4]; <= 1 mitigates the channlisation

#define BLADE_ATA_MODE_A_OUTPUT_NBEAM 2
#define BLADE_ATA_MODE_A_INTEGRATION_SIZE 32 // [1, 4]; <= 1 mitigates the channlisation
#define BLADE_ATA_MODE_A_OUTPUT_NPOL 1
#define BLADE_ATA_MODE_A_OUTPUT_INCOHERENT_BEAM false
#define BLADE_ATA_MODE_A_CIRCULAR_POLARIZATION false

#define BLADE_ATA_MODE_A_OUTPUT_N_BYTES 4
#define BLADE_ATA_MODE_A_OUTPUT_ELEMENT_T F32

#define BLADE_ATA_MODE_A_DATA_SIZE (\
  (BLADE_ATA_MODE_A_OUTPUT_NBEAM + (BLADE_ATA_MODE_A_OUTPUT_INCOHERENT_BEAM ? 1 : 0)) *\
  N_INPUT_CHANNELS *\
  N_INPUT_BLOCK_TIME *\
  BLADE_ATA_MODE_A_OUTPUT_NPOL *\
  BLADE_ATA_MODE_A_OUTPUT_N_BYTES /\
  BLADE_ATA_MODE_A_INTEGRATION_SIZE\
)

#endif