#ifndef _HPGUPPI_ATA_BLADE_MODE_H_
#define _HPGUPPI_ATA_BLADE_MODE_H_

#define BLADE_ATA_MODE_A 0
#define BLADE_ATA_MODE_B 1
#define BLADE_ATA_MODE_H 2

#define BLADE_ATA_MODE BLADE_ATA_MODE_H

#if BLADE_ATA_MODE == BLADE_ATA_MODE_A
#include "hpguppi_blade_ata_mode_a_config.h"
#include "hpguppi_blade_ata_mode_a_capi.h"

#define BLADE_ATA_CONFIG BLADE_ATA_MODE_A_CONFIG
#define BLADE_BLOCK_OUTPUT_DATA_SIZE BLADE_ATA_MODE_A_OUTPUT_DATA_SIZE
#define BLADE_BLOCK_DATA_SIZE BLADE_ATA_MODE_A_DATA_SIZE
#define BLADE_ATA_OUTPUT_ELEMENT_BYTES BLADE_ATA_MODE_A_OUTPUT_N_BYTES
#define BLADE_ATA_INPUT_NANT BLADE_ATA_MODE_A_INPUT_NANT
#define BLADE_ATA_OUTPUT_NBEAM BLADE_ATA_MODE_A_OUTPUT_NBEAM
#define BLADE_ATA_OUTPUT_INCOHERENT_BEAM BLADE_ATA_MODE_A_OUTPUT_INCOHERENT_BEAM

#define BLADE_ATA_OUTPUT_NBITS BLADE_ATA_OUTPUT_ELEMENT_BYTES*8
#define BLADE_ATA_OUTPUT_SAMPLE_TYPE "F32"

#define blade_ata_initialize blade_ata_a_initialize
#define blade_ata_get_output_size blade_ata_a_get_output_size

#define blade_ata_terminate blade_ata_a_terminate

#define blade_ata_set_block_time_mjd blade_ata_a_set_block_time_mjd
#define blade_ata_set_block_dut1 blade_ata_a_set_block_dut1

#define blade_ata_register_user_data blade_ata_a_register_user_data
#define blade_ata_register_input_buffer_prefetch_cb blade_ata_a_register_input_buffer_prefetch_cb
#define blade_ata_register_input_buffer_fetch_cb blade_ata_a_register_input_buffer_fetch_cb
#define blade_ata_register_input_buffer_enqueued_cb blade_ata_a_register_input_buffer_enqueued_cb
#define blade_ata_register_input_buffer_ready_cb blade_ata_a_register_input_buffer_ready_cb
#define blade_ata_register_output_buffer_fetch_cb blade_ata_a_register_output_buffer_fetch_cb
#define blade_ata_register_output_buffer_ready_cb blade_ata_a_register_output_buffer_ready_cb

#define blade_ata_register_blade_queued_input_clear_cb blade_ata_a_register_blade_queued_input_clear_cb
#define blade_ata_register_blade_queued_output_clear_cb blade_ata_a_register_blade_queued_output_clear_cb

#define blade_ata_compute_step blade_ata_a_compute_step


#endif // BLADE_ATA_MODE_A

#if BLADE_ATA_MODE == BLADE_ATA_MODE_B
#include "hpguppi_blade_ata_mode_b_config.h"
#include "hpguppi_blade_ata_mode_b_capi.h"

#define BLADE_ATA_CONFIG BLADE_ATA_MODE_B_CONFIG
#define BLADE_BLOCK_OUTPUT_DATA_SIZE BLADE_ATA_MODE_B_OUTPUT_DATA_SIZE
#define BLADE_BLOCK_DATA_SIZE BLADE_ATA_MODE_B_DATA_SIZE
#define BLADE_ATA_OUTPUT_ELEMENT_BYTES BLADE_ATA_MODE_B_OUTPUT_NCOMPLEX_BYTES
#define BLADE_ATA_INPUT_NANT BLADE_ATA_MODE_B_INPUT_NANT
#define BLADE_ATA_OUTPUT_NBEAM BLADE_ATA_MODE_B_OUTPUT_NBEAM
#define BLADE_ATA_OUTPUT_INCOHERENT_BEAM false

#define BLADE_ATA_OUTPUT_NBITS BLADE_ATA_MODE_B_OUTPUT_NCOMPLEX_BYTES*8/2
#define BLADE_ATA_OUTPUT_SAMPLE_TYPE (BLADE_ATA_MODE_B_OUTPUT_NCOMPLEX_BYTES == 8 ? "CF32" : "CF16")

#define blade_ata_initialize blade_ata_b_initialize
#define blade_ata_get_output_size blade_ata_b_get_output_size

#define blade_ata_terminate blade_ata_b_terminate

#define blade_ata_set_block_time_mjd blade_ata_b_set_block_time_mjd
#define blade_ata_set_block_dut1 blade_ata_b_set_block_dut1

#define blade_ata_register_user_data blade_ata_b_register_user_data
#define blade_ata_register_input_buffer_prefetch_cb blade_ata_b_register_input_buffer_prefetch_cb
#define blade_ata_register_input_buffer_fetch_cb blade_ata_b_register_input_buffer_fetch_cb
#define blade_ata_register_input_buffer_enqueued_cb blade_ata_b_register_input_buffer_enqueued_cb
#define blade_ata_register_input_buffer_ready_cb blade_ata_b_register_input_buffer_ready_cb
#define blade_ata_register_output_buffer_fetch_cb blade_ata_b_register_output_buffer_fetch_cb
#define blade_ata_register_output_buffer_ready_cb blade_ata_b_register_output_buffer_ready_cb

#define blade_ata_register_blade_queued_input_clear_cb blade_ata_b_register_blade_queued_input_clear_cb
#define blade_ata_register_blade_queued_output_clear_cb blade_ata_b_register_blade_queued_output_clear_cb

#define blade_ata_compute_step blade_ata_b_compute_step

#endif // BLADE_ATA_MODE_B

#if BLADE_ATA_MODE == BLADE_ATA_MODE_H
#include "hpguppi_blade_ata_mode_h_config.h"
#include "hpguppi_blade_ata_mode_h_capi.h"

#define BLADE_ATA_CONFIG BLADE_ATA_MODE_H_CONFIG
#define BLADE_BLOCK_OUTPUT_DATA_SIZE BLADE_ATA_MODE_H_OUTPUT_DATA_SIZE
#define BLADE_BLOCK_DATA_SIZE BLADE_ATA_MODE_H_DATA_SIZE
#define BLADE_ATA_OUTPUT_ELEMENT_BYTES BLADE_ATA_MODE_H_OUTPUT_N_BYTES
#define BLADE_ATA_INPUT_NANT BLADE_ATA_MODE_H_INPUT_NANT
#define BLADE_ATA_OUTPUT_NBEAM BLADE_ATA_MODE_H_OUTPUT_NBEAM
#define BLADE_ATA_OUTPUT_INCOHERENT_BEAM BLADE_ATA_MODE_H_OUTPUT_INCOHERENT_BEAM

#define BLADE_ATA_OUTPUT_NBITS BLADE_ATA_OUTPUT_ELEMENT_BYTES*8
#define BLADE_ATA_OUTPUT_SAMPLE_TYPE "F32"

#define blade_ata_initialize blade_ata_h_initialize
#define blade_ata_get_output_size blade_ata_h_get_output_size

#define blade_ata_terminate blade_ata_h_terminate

#define blade_ata_set_block_time_mjd blade_ata_h_set_block_time_mjd
#define blade_ata_set_block_dut1 blade_ata_h_set_block_dut1

#define blade_ata_register_user_data blade_ata_h_register_user_data
#define blade_ata_register_input_buffer_prefetch_cb blade_ata_h_register_input_buffer_prefetch_cb
#define blade_ata_register_input_buffer_fetch_cb blade_ata_h_register_input_buffer_fetch_cb
#define blade_ata_register_input_buffer_enqueued_cb blade_ata_h_register_input_buffer_enqueued_cb
#define blade_ata_register_input_buffer_ready_cb blade_ata_h_register_input_buffer_ready_cb
#define blade_ata_register_output_buffer_fetch_cb blade_ata_h_register_output_buffer_fetch_cb
#define blade_ata_register_output_buffer_ready_cb blade_ata_h_register_output_buffer_ready_cb

#define blade_ata_register_blade_queued_input_clear_cb blade_ata_h_register_blade_queued_input_clear_cb
#define blade_ata_register_blade_queued_output_clear_cb blade_ata_h_register_blade_queued_output_clear_cb

#define blade_ata_compute_step blade_ata_h_compute_step

#endif // BLADE_ATA_MODE_H


#endif // _HPGUPPI_ATA_BLADE_MODE_H_
