#ifndef BLADE_ATA_MODE_H_CONFIG_H
#define BLADE_ATA_MODE_H_CONFIG_H

#include "config_input_shape.h"

#define BLADE_ATA_MODE_H_CHANNELIZER_RATE 1 // [1, 4]; <= 1 mitigates the channlisation

#define BLADE_ATA_MODE_H_OUTPUT_NBEAM 2
#define BLADE_ATA_MODE_H_ACCUMULATE_RATE 32 // [1]; <= 1 mitigates the accumulation
#define BLADE_ATA_MODE_H_INTEGRATION_SIZE 32 // [1]; <= 1 mitigates the integration
#define BLADE_ATA_MODE_H_OUTPUT_NPOL 1
#define BLADE_ATA_MODE_H_OUTPUT_INCOHERENT_BEAM false
#define BLADE_ATA_MODE_H_CIRCULAR_POLARIZATION false

#define BLADE_ATA_MODE_H_OUTPUT_N_BYTES 4
#define BLADE_ATA_MODE_H_OUTPUT_ELEMENT_T F32

#define BLADE_ATA_MODE_H_DATA_SIZE (\
  (BLADE_ATA_MODE_H_OUTPUT_NBEAM + (BLADE_ATA_MODE_H_OUTPUT_INCOHERENT_BEAM ? 1 : 0)) *\
  N_INPUT_CHANNELS *\
  N_INPUT_BLOCK_TIME *\
  BLADE_ATA_MODE_H_ACCUMULATE_RATE *\
  BLADE_ATA_MODE_H_OUTPUT_NPOL *\
  BLADE_ATA_MODE_H_OUTPUT_N_BYTES\
)

#endif