#ifndef BLADE_ATA_MODE_C_CONFIG_H
#define BLADE_ATA_MODE_C_CONFIG_H

#define BLADE_ATA_MODE_C_INTEGRATION_SIZE 16 // [1, 4]; <= 1 mitigates the integration

#define BLADE_ATA_MODE_C_INPUT_NANT 20
#define BLADE_ATA_MODE_C_INPUT_NCOMPLEX_BYTES 2

#define BLADE_ATA_MODE_C_ANT_NCHAN 192
#define BLADE_ATA_MODE_C_NTIME 8192
#define BLADE_ATA_MODE_C_NPOL 2

#define BLADE_ATA_MODE_C_OUTPUT_NBEAM 2
#define BLADE_ATA_MODE_C_OUTPUT_NCOMPLEX_BYTES 8

#define BLADE_ATA_MODE_C_OUTPUT_MEMCPY2D_PAD 0 // zero makes memcpy2D effectively 1D
#define BLADE_ATA_MODE_C_OUTPUT_MEMCPY2D_WIDTH 8192

#define BLADE_ATA_MODE_C_OUTPUT_ELEMENT_T CF32

#define BLADE_ATA_MODE_C_OUTPUT_MEMCPY2D_DPITCH (BLADE_ATA_MODE_C_OUTPUT_MEMCPY2D_WIDTH+BLADE_ATA_MODE_C_OUTPUT_MEMCPY2D_PAD)

#define BLADE_ATA_MODE_C_OUTPUT_DATA_SIZE (BLADE_ATA_MODE_C_INPUT_NANT*(BLADE_ATA_MODE_C_INPUT_NANT+1)/2 *\
                               BLADE_ATA_MODE_C_ANT_NCHAN *\
                               (BLADE_ATA_MODE_C_NTIME/BLADE_ATA_MODE_C_INTEGRATION_SIZE) *\
                               4 *\
                               BLADE_ATA_MODE_C_OUTPUT_NCOMPLEX_BYTES)

#define BLADE_ATA_MODE_C_DATA_SIZE ((BLADE_ATA_MODE_C_OUTPUT_DATA_SIZE/BLADE_ATA_MODE_C_OUTPUT_MEMCPY2D_WIDTH)*BLADE_ATA_MODE_C_OUTPUT_MEMCPY2D_DPITCH)

#endif