#ifndef BLADE_ATA_MODE_X_CONFIG_H
#define BLADE_ATA_MODE_X_CONFIG_H

#define BLADE_ATA_MODE_X_INTEGRATION_SIZE 262144 // just a fallback default
#define BLADE_ATA_MODE_X_INTEGRATION_FACTOR 1
#define BLADE_ATA_MODE_X_CHANNELIZER_RATE 16384 // 1 mitigates the channelization

#define BLADE_ATA_MODE_X_INPUT_NANT 28
#define BLADE_ATA_MODE_X_INPUT_NCOMPLEX_BYTES 2

#if BLADE_ATA_MODE_X_CHANNELIZER_RATE == 1
// Continuum correlator
#define BLADE_ATA_MODE_X_ANT_NCHAN 192
#define BLADE_ATA_MODE_X_NTIME 8192
#else
// spectral-line correlator # 16 MHz
#define BLADE_ATA_MODE_X_ANT_NCHAN 1
#define BLADE_ATA_MODE_X_NTIME BLADE_ATA_MODE_X_CHANNELIZER_RATE
#endif

#define BLADE_ATA_MODE_X_NPOL 2

#define BLADE_ATA_MODE_X_OUTPUT_NBEAM 1
#define BLADE_ATA_MODE_X_OUTPUT_NCOMPLEX_BYTES 8

#define BLADE_ATA_MODE_X_OUTPUT_MEMCPY2D_PAD 0 // zero makes memcpy2D effectively 1D
#define BLADE_ATA_MODE_X_OUTPUT_MEMCPY2D_WIDTH 8192

#define BLADE_ATA_MODE_X_CONJUGATION_INDEX 0

#define BLADE_ATA_MODE_X_OUTPUT_ELEMENT_T CF32

#define BLADE_ATA_MODE_X_OUTPUT_MEMCPY2D_DPITCH (BLADE_ATA_MODE_X_OUTPUT_MEMCPY2D_WIDTH+BLADE_ATA_MODE_X_OUTPUT_MEMCPY2D_PAD)

#define BLADE_ATA_MODE_X_OUTPUT_DATA_SIZE ((size_t)(BLADE_ATA_MODE_X_INPUT_NANT*(BLADE_ATA_MODE_X_INPUT_NANT+1)/2) *\
                               (size_t)(BLADE_ATA_MODE_X_ANT_NCHAN*BLADE_ATA_MODE_X_CHANNELIZER_RATE) *\
                               1 *\
                               4 *\
                               BLADE_ATA_MODE_X_OUTPUT_NCOMPLEX_BYTES)

#define BLADE_ATA_MODE_X_DATA_SIZE BLADE_ATA_MODE_X_OUTPUT_DATA_SIZE
//((BLADE_ATA_MODE_X_OUTPUT_DATA_SIZE/BLADE_ATA_MODE_X_OUTPUT_MEMCPY2D_WIDTH)*BLADE_ATA_MODE_X_OUTPUT_MEMCPY2D_DPITCH)

#endif